module.exports = {
    "Número de expediente": "",
    "Número de registro": "",
    "Fecha de presentación": "",
    "Fecha de inicio de uso": "",
    "Fecha de concesión": "",
    "Fecha de vigencia": "",
    "Fecha de publicación de la solicitud": "",
    "Denominación": "",
    "Descripción de la marca": "",
    "Tipo de solicitud": "",
    "Tipo de marca": "",
    "Elementos sobre los cuales no se solicita protección": "",
    "Número de registro internacional": "",
    "Traducción": "",
    "Transliteración": "",
    "Imagen": "",
    "Código de la clasificación de Viena": "",
    "Nombre": "",
    "Dirección": "",
    "Población": "",
    "Código postal": "",
    "País": "",
    "Nacionalidad": "",
    "RFC": "",
    "Teléfono": "",
    "Fax": "",
    "E-mail": "",
    "Dirección.1": "",
    "Población.1": "",
    "Código postal.1": "",
    "País.1": "",
    "Clase": "",
    "Descripción": "",
    "Nombre.1": "",
    "Dirección.2": "",
    "Población.2": "",
    "Código postal.2": "",
    "País.2": "",
    "Nacionalidad.1": "",
    "RFC.1": "",
    "Teléfono.1": "",
    "Fax.1": "",
    "E-mail.1": "",
    "Folio de entrada del trámite": "",
    "Año de recepción": "",
    "Descripción.1": "",
    "Fecha de inicio": "",
    "Fecha de conclusión": "",
    "Fecha de inicio": "",
    "Fecha de inicio": "",
    "Imagen.1": "",
}